"""Replaceable source adapters and auditable sync orchestration."""

from trainingos.ingestion.fit import (
    FIT_PARSER,
    MANUAL_FIT_SOURCE,
    FitImportPayload,
    FitMessage,
    ManualFitAdapter,
    ManualFitHandler,
    ParsedFitActivity,
    parse_fit_messages,
    read_fit_messages,
)
from trainingos.ingestion.garmin import (
    GARMIN_SOURCE,
    GarminActivityAdapter,
    GarminActivityPage,
    GarminActivitySummary,
    GarminClient,
)
from trainingos.ingestion.raw import RawArtifact, RawArtifactStore
from trainingos.ingestion.sync import (
    RecordHandler,
    RetryPolicy,
    SourceAdapter,
    SyncDisposition,
    SyncError,
    SyncOptions,
    SyncPage,
    SyncProtocolError,
    SyncRecord,
    SyncReport,
    SyncRunner,
    SyncStatus,
)
from trainingos.ingestion.weather import (
    HistoricalWeatherAdapter,
    WeatherEnricher,
    WeatherFetchResult,
    WeatherRequest,
    temperature_celsius,
)

__all__ = [
    "FIT_PARSER",
    "GARMIN_SOURCE",
    "MANUAL_FIT_SOURCE",
    "FitImportPayload",
    "FitMessage",
    "GarminActivityAdapter",
    "GarminActivityPage",
    "GarminActivitySummary",
    "GarminClient",
    "HistoricalWeatherAdapter",
    "ManualFitAdapter",
    "ManualFitHandler",
    "ParsedFitActivity",
    "RawArtifact",
    "RawArtifactStore",
    "RecordHandler",
    "RetryPolicy",
    "SourceAdapter",
    "SyncDisposition",
    "SyncError",
    "SyncOptions",
    "SyncPage",
    "SyncProtocolError",
    "SyncRecord",
    "SyncReport",
    "SyncRunner",
    "SyncStatus",
    "WeatherEnricher",
    "WeatherFetchResult",
    "WeatherRequest",
    "parse_fit_messages",
    "read_fit_messages",
    "temperature_celsius",
]
